//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlDataAccess.Queries.Exp3 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Experiment3Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Experiment3Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SqlDataAccess.Queries.Exp3.Experiment3Sql", typeof(Experiment3Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Employee (id, firstname, lastname, email, birthday, title, phone)
        ///VALUES (@Id, @FirstName, @LastName, @Email, @Birthday, @Title, @Phone);
        ///
        ///INSERT INTO developer (id, seniority, yearsofexperience, isremote)
        ///VALUES (@Id, @Seniority, @YearsOfExperience, @IsRemote);
        ///
        ///INSERT INTO intern (id, university, studyyear, city)
        ///VALUES (@Id, @University, @StudyYear, @City);
        ///
        ///INSERT INTO manager (id, department, realisedproject, method)
        ///VALUES (@Id, @Department, @RealisedProject, @Method);
        ///
        ///INSERT  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Employee;
        ///
        ///SELECT e.id, e.firstname, e.lastname, e.email, e.birthday, e.title, e.phone, m.department, m.realisedProject, m.method 
        ///FROM Employee e INNER JOIN Manager m ON e.id = m.id;
        ///
        ///SELECT e.id, e.firstname, e.lastname, e.email, e.birthday, e.title, e.phone, d.seniority, d.yearsOfExperience, d.isRemote, sd.programmingLanguage, sd.ide, sd.isFullStack 
        ///FROM Employee e INNER JOIN Developer d ON e.id = d.id INNER JOIN SoftwareDeveloper sd ON d.id = sd.id;
        ///
        ///SELECT * FROM Employee WHERE i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE IF EXISTS SoftwareDeveloper;
        ///DROP TABLE IF EXISTS DatabaseDeveloper;
        ///DROP TABLE IF EXISTS Developer;
        ///DROP TABLE IF EXISTS Intern;
        ///DROP TABLE IF EXISTS Manager;
        ///DROP TABLE IF EXISTS Employee;
        ///
        ///CREATE TABLE Employee (
        ///    id BIGINT PRIMARY KEY,
        ///    firstname NVARCHAR(255) NOT NULL,
        ///    lastname NVARCHAR(255) NOT NULL,
        ///    email NVARCHAR(255) NOT NULL,
        ///    birthday DATE NOT NULL,
        ///    title NVARCHAR(255) NOT NULL,
        ///    phone NVARCHAR(50) NOT NULL
        ///);
        ///
        ///CREATE TABLE Developer (
        ///    id B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Employee SET phone = @Phone WHERE id = @EmployeeId;
        ///
        ///UPDATE Manager SET method = @Method WHERE id = @ManagerId;
        ///
        ///UPDATE SoftwareDeveloper SET isFullStack = 1 WHERE id = @SoftwareDeveloperId;
        ///
        ///UPDATE Manager 
        ///SET method = &apos;Lean&apos;
        ///WHERE department IN (&apos;IT&apos;,&apos;Logistics&apos;)
        ///AND id IN (SELECT id FROM Employee WHERE DATEDIFF(YEAR, e.birthday, GETDATE()) BETWEEN 40 AND 50);
        ///
        ///UPDATE SoftwareDeveloper
        ///SET isFullStack = 1
        ///WHERE id IN(SELECT id FROM Developer WHERE yearsOfExperience &gt; 10)
        ///AND id IN(SE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
