//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HybridDataAccess.Queries.Exp3 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Experiment3Hybrid {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Experiment3Hybrid() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HybridDataAccess.Queries.Exp3.Experiment3Hybrid", typeof(Experiment3Hybrid).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Employee (id, firstname, lastname, email, birthday, title, phone,manager)
        ///VALUES (@Id, @FirstName, @LastName, @Email, @Birthday, @Title, @Phone,@Manager);
        ///
        ///INSERT INTO Developer (id, seniority, yearsofexperience, isremote,softwareDeveloper)
        ///VALUES (@Id, @Seniority, @YearsOfExperience, @IsRemote,@SoftwareDeveloper);.
        /// </summary>
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Employee;
        ///
        ///SELECT  e.id, e.firstname, e.lastname, e.email, e.birthday, e.title, e.phone, m.department, m.realisedProject, m.method
        ///FROM Employee e CROSS APPLY OPENJSON(manager) WITH(
        ///	Department NVARCHAR(100) &apos;$.Department&apos;,
        ///	RealisedProject INT &apos;$.RealisedProject&apos;,
        ///	Method NVARCHAR(20) &apos;$.Method&apos;
        ///)AS m
        ///WHERE manager is not null;
        ///
        ///SELECT e.id, e.firstname, e.lastname, e.email, e.birthday, e.title, e.phone, d.seniority, d.yearsOfExperience, d.isRemote, sd.programmingLanguage, sd.ide,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE IF EXISTS Developer;
        ///DROP TABLE IF EXISTS Employee;
        ///
        ///CREATE TABLE Employee (
        ///    id BIGINT PRIMARY KEY,
        ///    firstname NVARCHAR(255) NOT NULL,
        ///    lastname NVARCHAR(255) NOT NULL,
        ///    email NVARCHAR(255) NOT NULL,
        ///    birthday DATE NOT NULL,
        ///    title NVARCHAR(255) NOT NULL,
        ///    phone NVARCHAR(50) NOT NULL,
        ///    manager NVARCHAR(MAX) NULL
        ///);
        ///
        ///CREATE TABLE Developer (
        ///    id BIGINT PRIMARY KEY FOREIGN KEY REFERENCES employee(id) ON DELETE CASCADE,
        ///    seniority NVARCHAR(255) NOT NULL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Employee SET phone = @Phone WHERE id = @EmployeeId;
        ///
        ///UPDATE Employee SET manager = JSON_MODIFY(manager,&apos;$.Method&apos;,@Method) WHERE id = @ManagerId AND manager is not null;
        ///
        ///UPDATE Developer SET softwareDeveloper = JSON_MODIFY(softwareDeveloper,&apos;$.IsFullStack&apos;,1) 
        ///WHERE id = @SoftwareDeveloperId AND softwareDeveloper is not null;
        ///
        ///UPDATE Employee 
        ///SET manager = JSON_MODIFY(manager,&apos;$.Method&apos;,&apos;Lean&apos;)
        ///WHERE JSON_VALUE(manager,&apos;$.Department&apos;) IN (&apos;IT&apos;,&apos;Logistics&apos;) AND
        ///DATEDIFF(YEAR, birthday, GET [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
