//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlDataAccess.Queries.Exp2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Experiment2Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Experiment2Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SqlDataAccess.Queries.Exp2.Experiment2Sql", typeof(Experiment2Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Unos podataka u tabelu Department
        ///INSERT INTO Department (id, name, location)
        ///VALUES (@Id, @Name, @Location);
        ///
        ///-- Unos podataka u tabelu Employee
        ///INSERT INTO Employee (id, first_name, last_name, email, birth_day, title, phone,team_id)
        ///VALUES (@Id, @FirstName, @LastName, @Email, @BirthDay, @Title, @Phone,@TeamId);
        ///
        ///-- Unos podataka u tabelu Team
        ///INSERT INTO Team (id, name, status, description, department_id, leader_id)
        ///VALUES (@Id, @Name, @Status, @Description, @DepartmentId, @LeaderId);
        ///
        ///.
        /// </summary>
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- 0. Vrati sve timove i zaposlene po department *
        ///SELECT *
        ///FROM Department d 
        ///LEFT JOIN Team t ON t.department_id=d.id
        ///INNER JOIN Employee l ON t.leader_id=l.id
        ///LEFT JOIN Employee e ON e.team_id=t.id;
        ///-- 1. Vrati sve timove i zaposlene po department naziv
        ///SELECT d.id DepartementId,d.name DepartmentName,d.location DepartmentLocation,
        ///t.id TeamId, t.name TeamName, t.status TeamStatus, t.description TeamDescription,
        ///l.id LeadId, l.first_name LeadFirstName, l.last_name LeadLastName, l.email LeadEmail, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///ALTER TABLE Employee DROP CONSTRAINT IF EXISTS fk_employee_team;
        ///ALTER TABLE Team DROP CONSTRAINT IF EXISTS fk_team_department;
        ///-- Brisanje tabele employee ako postoji
        ///DROP TABLE IF EXISTS Employee;
        ///
        ///-- Brisanje tabele team ako postoji
        ///DROP TABLE IF EXISTS Team;
        ///
        ///-- Brisanje tabele department ako postoji
        ///DROP TABLE IF EXISTS Department;
        ///
        ///-- Kreiranje tabele department
        ///CREATE TABLE Department (
        ///    id BIGINT PRIMARY KEY,
        ///    name NVARCHAR(255) NULL,
        ///    location NVARCHAR(255) NULL
        ///);
        ///
        ///--  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- 1. Update status by id
        ///UPDATE Team SET Status=@Status WHERE id=@Id;
        ///
        ///-- 2. Update phone by Id
        ///UPDATE Employee SET phone=@Phone WHERE id=@Id;
        ///
        ///-- 3. By Location
        ///UPDATE Team 
        ///SET description=@Description 
        ///WHERE department_id IN (SELECT id FROM Department WHERE location=&apos;Prague&apos;);
        ///
        ///-- 4. 
        ///UPDATE Team
        ///SET description = &apos;Very Young&apos;
        ///WHERE id IN (
        ///    SELECT t.id
        ///    FROM Team t
        ///    JOIN Employee e ON e.team_id = t.id
        ///    WHERE DATEDIFF(YEAR, e.birth_day, GETDATE()) &lt; 20
        ///);
        ///-- 5.
        ///UPDATE Te [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
