//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlDataAccess.Queries.Exp1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Experiment1Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Experiment1Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SqlDataAccess.Queries.Exp1.Experiment1Sql", typeof(Experiment1Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- 1. Delete all Tasks
        ///DELETE FROM dbo.Task;
        ///-- 2. Delete By Id
        ///DELETE FROM dbo.Task WHERE id=@Id
        ///-- 3. Delete By Status
        ///DELETE FROM dbo.Task WHERE status=@Status;
        ///-- 4. Delete by Responsible id
        ///DELETE FROM dbo.Task WHERE responsible= (SELECT id FROM dbo.Employee WHERE id=@Id);
        ///-- 5. Delete By Supervisor FirstName
        ///DELETE FROM dbo.Task WHERE responsible= (SELECT id FROM dbo.Employee WHERE firstName LIKE &apos;J%&apos;);
        ///.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Employee(id,firstName,lastName,email,birthDay,title,phone)
        ///VALUES(@EmployeeId,@EmployeeFirstname,@EmployeeLastname,@EmployeeEmail,@EmployeeBirthday,@EmployeeTitle,@EmployeePhone);
        ///
        ///INSERT INTO Task(id,name,description,priority,deadline,status,responsible,supervisor)
        ///VALUES(@TaskId,@TaskName,@TaskDescription,@TaskPriority,@TaskDeadline,@TaskStatus,@Responsible,@Supervisor);
        ///
        ///INSERT INTO EmployeeTask(employeeId,taskId) VALUES(@EmployeeId,@TaskId);
        ///.
        /// </summary>
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --1. Get All
        ///SELECT * 
        ///FROM dbo.Task t 
        ///INNER JOIN dbo.Employee r ON (r.id=t.responsible)
        ///LEFT JOIN dbo.Employee s ON (s.id=t.supervisor)
        ///LEFT JOIN dbo.EmployeeTask et ON (t.id=et.taskId)
        ///INNER JOIN dbo.Employee em ON (em.id=et.employeeId);
        ///--2. Get all but with names
        ///SELECT t.id TaskId, t.name TaskName, t.description TaskDescription, t.priority TaskPriority,t.deadline TaskDeadline, t.status TaskStatus,
        ///r.Id ResponsibleId, r.email ResponsibleEmail, r.firstName ResponsibleFirstName, r.lastName Respo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE IF EXISTS EmployeeTask;
        ///DROP TABLE IF EXISTS Task;
        ///DROP TABLE IF EXISTS Employee;
        ///
        ///CREATE TABLE Employee(
        ///	id BIGINT CONSTRAINT employee_pk PRIMARY KEY,
        ///	firstName NVARCHAR(50) NULL,
        ///	lastName NVARCHAR(50) NULL,
        ///	email NVARCHAR(80) NULL,
        ///	birthDay DATETIME DEFAULT GETDATE(),
        ///	title NVARCHAR(100), 
        ///	phone NVARCHAR(20),
        ///);
        ///CREATE TABLE Task(
        ///	id BIGINT CONSTRAINT task_id PRIMARY KEY,
        ///	name NVARCHAR(100) NULL,
        ///	description NVARCHAR(1000) NULL,
        ///	priority INT DEFAULT 0,
        ///	deadline DAT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- 1. Update Task expired and pedning
        ///UPDATE dbo.Task SET Status = &apos;Cancelled&apos; WHERE Deadline &lt; GETDATE() AND Status = &apos;Pending&apos;;
        ///-- 2. Update phone by Id,
        ///UPDATE dbo.Employee SET phone=@Phone WHERE id=@Id;
        ///-- 3. Update phone by Email,
        ///UPDATE dbo.Employee SET phone=@Phone WHERE email=@Email;
        ///-- 4. Update deadline for priority and deadline
        ///UPDATE dbo.Task
        ///SET Deadline = DATEADD(DAY, 5, Deadline) 
        ///WHERE Priority &lt; 4 
        ///  AND Deadline BETWEEN GETDATE() AND DATEADD(DAY, 3, GETDATE());
        ///-- 5. Update dead [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
